version: '3.7'
services:
  db:
    image: mariadb
    restart: always
    command: mysqld --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: superSecrete
    volumes:
      - ./dbData:/var/lib/mysql
    ports:
      - 3307:3306